const pointsOfLetters = {
  A: 1,
  B: 3,
  C: 8,
  D: 1,
  E: 1,
  F: 3,
  G: 2,
  H: 3,
  I: 1,
  J: 7,
  K: 3,
  L: 2,
  M: 3,
  N: 1,
  O: 2,
  P: 4,
  R: 1,
  S: 1,
  T: 1,
  U: 4,
  V: 3,
  X: 8,
  Y: 7,
  Z: 8,
  Å: 4,
  Ä: 4,
  Ö: 4
}

const mockPossibleWords = 
[
  { word: 'OHÅGAT', value: 13 },
  { word: 'MANTÅG', value: 12 },
  { word: 'MÅNGET', value: 12 },
  { word: 'ÅHMAN', value: 12 },
  { word: 'HÅGAT', value: 11 },
  { word: 'HÅGEN', value: 11 },
  { word: 'MONTAGE', value: 11 },
  { word: 'MEGATON', value: 11 },
  { word: 'MÅGEN', value: 11 },
  { word: 'MÅNGA', value: 11 },
  { word: 'MÅNGT', value: 11 },
  { word: 'OMTAGEN', value: 11 },
  { word: 'HETMAN', value: 10 },
  { word: 'HÅGA', value: 10 },
  { word: 'HÅNAT', value: 10 },
  { word: 'HÅNET', value: 10 },
  { word: 'MAGONT', value: 10 },
  { word: 'MOGNAT', value: 10 },
  { word: 'MÅNAT', value: 10 },
  { word: 'OHMEN', value: 10 },
  { word: 'OMEGAT', value: 10 },
  { word: 'OMEGAN', value: 10 },
  { word: 'THEMAN', value: 10 },
  { word: 'ÅTAGEN', value: 10 },
  { word: 'NÅGOT', value: 10 },
  { word: 'ATOMEN', value: 9 },
  { word: 'HANGET', value: 9 },
  { word: 'HÅG', value: 9 },
  { word: 'HÅNA', value: 9 },
  { word: 'MAGNET', value: 9 },
  { word: 'MANGO', value: 9 },
  { word: 'MOGET', value: 9 },
  { word: 'MOGEN', value: 9 },
  { word: 'MOGNA', value: 9 },
  { word: 'MÅG', value: 9 },
  { word: 'MÅNA', value: 9 },
  { word: 'MÅNE', value: 9 },
  { word: 'MÅNT', value: 9 },
  { word: 'OMEGA', value: 9 },
  { word: 'OMTAG', value: 9 },
  { word: 'GENOM', value: 9 },
  { word: 'GÅTAN', value: 9 },
  { word: 'GÅTEN', value: 9 },
  { word: 'TÅGAN', value: 9 },
  { word: 'TÅGEN', value: 9 },
  { word: 'TÅNGE', value: 9 },
  { word: 'ÅMAT', value: 9 },
  { word: 'ÅMAN', value: 9 },
  { word: 'ÅMEN', value: 9 },
  { word: 'ÅTOG', value: 9 },
  { word: 'ÅNGAT', value: 9 },
  { word: 'ANGÅ', value: 8 },
  { word: 'HAMN', value: 8 },
  { word: 'HAGEN', value: 8 },
  { word: 'HOTEN', value: 8 },
  { word: 'HÅN', value: 8 },
  { word: 'MAGEN', value: 8 },
  { word: 'MÅN', value: 8 },
  { word: 'OHM', value: 8 },
  { word: 'OMGE', value: 8 },
  { word: 'GAMET', value: 8 },
  { word: 'GAMEN', value: 8 },
  { word: 'GÅTA', value: 8 },
  { word: 'GNOM', value: 8 },
  { word: 'TÅGA', value: 8 },
  { word: 'TÅNG', value: 8 },
  { word: 'ÅMA', value: 8 },
  { word: 'ÅTAG', value: 8 },
  { word: 'ÅNGA', value: 8 },
  { word: 'ÅNGE', value: 8 },
  { word: 'NOTAM', value: 8 },
  { word: 'AMTEN', value: 7 },
  { word: 'ATOM', value: 7 },
  { word: 'ANTOG', value: 7 },
  { word: 'HAGE', value: 7 },
  { word: 'HANG', value: 7 },
  { word: 'HOAT', value: 7 },
  { word: 'HOTA', value: 7 },
  { word: 'HONA', value: 7 },
  { word: 'HEM', value: 7 },
  { word: 'MAGE', value: 7 },
  { word: 'MATEN', value: 7 },
  { word: 'MANET', value: 7 },
  { word: 'MOTA', value: 7 },
  { word: 'MONA', value: 7 },
  { word: 'METAN', value: 7 },
  { word: 'MENAT', value: 7 },
  { word: 'MENTA', value: 7 },
  { word: 'MÅ', value: 7 },
  { word: 'OMAN', value: 7 },
  { word: 'OMEN', value: 7 },
  { word: 'EMOT', value: 7 },
  { word: 'EGONA', value: 7 },
  { word: 'GAME', value: 7 },
  { word: 'GOM', value: 7 },
  { word: 'GOTEN', value: 7 },
  { word: 'GONAT', value: 7 },
  { word: 'GÅT', value: 7 },
  { word: 'TANGO', value: 7 },
  { word: 'THEO', value: 7 },
]

module.exports = {
  pointsOfLetters,
  mockPossibleWords
}